import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

function readSource(relPath: string): string {
  const url = new URL(relPath, import.meta.url);
  return readFileSync(fileURLToPath(url), "utf-8");
}

function readJson(relPath: string): unknown {
  return JSON.parse(readSource(relPath));
}

describe("federation settings placement", () => {
  it("group bridges is a recognized group settings tab without a global federation tab", () => {
    expect(readSource("./types.ts")).toContain('| "connections"');
    expect(readSource("./types.ts")).not.toContain('| "federation"');
    expect(readSource("./settingsLastLocation.ts")).toContain('"connections"');
    expect(readSource("./settingsLastLocation.ts")).not.toContain('"federation"');
  });

  it("SettingsModal registers group Group Bridges without an empty Global Federation page", () => {
    const src = readSource("../../SettingsModal.tsx");
    expect(src).toContain('id: "connections"');
    expect(src).toContain('activeTab === "connections"');
    expect(src).not.toContain('id: "federation"');
    expect(src).not.toContain('activeTab === "federation"');
    expect(src).not.toContain("FederationRegistrationSection");
    expect(src).toContain("FederationConnectionsSection");
  });

  it("WebAccessTab no longer embeds the federation form", () => {
    const src = readSource("./WebAccessTab.tsx");
    expect(src).not.toContain("FederationRegistrationSection");
  });

  it("group Connections owns federation session pairing and always filters by current group", () => {
    const src = readSource("./FederationConnectionsSection.tsx");
    expect(src).toContain("FederationSessionPairingSection");
    expect(src).toContain("groupId");
    expect(src).toContain("fetchFederationPairingRequests(groupId)");
    expect(src).toContain("fetchFederationTrusts(groupId)");
    expect(src).toContain("fetchFederationStatus(groupId)");
  });

  it("group Connections syncs submitted and pending outbound requests on refresh", () => {
    const src = readSource("./FederationConnectionsSection.tsx");
    expect(src).toContain("projectSyncableOutbounds");
    expect(src).toContain("syncFederationPairingOutbound(outbound.outbound_id)");
    expect(src).not.toContain('String(outbound.status || "") === "submitted"');
  });

  it("federation session pairing section does not expose direct registration fields or call direct register", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).not.toContain("Remote URL");
    expect(src).not.toContain("Credential reference");
    expect(src).not.toContain("Remote group URL");
    expect(src).not.toContain("DHT");
    expect(src).not.toContain("relay");
    expect(src).not.toContain("hole punching");
    expect(src).not.toContain("registerFederation");
    expect(src).toContain("createFederationPairingInvite");
    expect(src).toContain("createFederationRemotePairingRequest");
    expect(src).toContain("approveFederationPairingRequest");
  });

  it("federation session connection info copy uses the shared clipboard fallback", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("copyTextToClipboard");
    expect(src).not.toContain("navigator.clipboard?.writeText");
  });

  it("federation session pairing is cross-instance first and demotes same-instance codes", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain('t("federation.connectRemoteCcccGroup")');
    expect(src).toContain('t("federation.issuerEndpoint")');
    expect(src).toContain('t("federation.issuerEndpointLocalOnlyHelp")');
    expect(src).toContain('t("federation.sameInstanceFallbackDetected")');
    expect(src).toContain('t("federation.sameInstanceFallbackHelp")');
    expect(src).toContain("isSameInstancePairingInput");
    const modelSrc = readSource("./federationPairingModel.ts");
    expect(modelSrc).toContain("issuer_endpoint");
    expect(modelSrc).toContain("expires_at");
    expect(modelSrc).toContain("nonce");
    expect(modelSrc).toContain("integrity");
    expect(src).not.toContain('placeholder="ABCD-1234"');
  });

  it("federation session connection info is generated by the backend after invite creation", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("normalizeIssuerEndpoint(issuerEndpoint)");
    expect(src).toContain("createFederationPairingConnectionInfo");
    expect(src.indexOf("createFederationPairingInvite")).toBeLessThan(src.indexOf("createFederationPairingConnectionInfo"));
    expect(src).not.toContain("assertSha256Available();");
    expect(src).not.toContain("crypto.subtle.digest");
    expect(src).toContain('t("federation.issuerEndpointInvalid")');
    expect(src).toContain("userFacingPairingErrorKey");
    expect(src).not.toContain('setInviteError(infoResp.error.message || t("federation.createInviteFailed"))');
  });

  it("federation session connection info includes the current group title for remote display", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("issuerGroupTitle");
    expect(src).toContain("issuerGroupTitle: currentGroupTitle || currentGroupId");
  });

  it("federation session pairing submits remote issuer payloads through the remote pairing endpoint", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("parsed.isRemote && parsed.payload");
    expect(src).toContain("createFederationRemotePairingRequest");
    expect(src).toContain('t("federation.remotePayloadDetected")');
    expect(src).toContain('t("federation.remotePayloadTarget"');
  });

  it("federation session pairing revocation invalidates composer federation route suggestions", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    const revokeStart = src.indexOf("const revokeTrustedPeer");
    expect(revokeStart).toBeGreaterThan(0);
    const revokeSrc = src.slice(revokeStart, src.indexOf("const deleteOutbound", revokeStart));
    expect(revokeSrc).toContain("publishFederationPairingChanged(currentGroupId)");
    expect(revokeSrc.indexOf("revokeFederationTrust(tid)")).toBeLessThan(revokeSrc.indexOf("publishFederationPairingChanged(currentGroupId)"));
  });

  it("federation session pairing section uses the current group without local group selection", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("currentGroupId");
    expect(src).not.toContain("setSelectedGroupId");
    expect(src).not.toContain('t("federation.localGroup")');
    expect(src).not.toContain('t("federation.selectGroup")');
    expect(src).not.toContain('t("federation.peerGroupId")');
  });

  it("federation session pairing is an approval workbench, not a direct registration form", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain('useTranslation("settings")');
    expect(src).toContain('t("federation.connectRemoteCcccGroup")');
    expect(src).toContain('t("federation.createConnectionInfo")');
    expect(src).toContain('t("federation.pasteConnectionInfo")');
    expect(src).toContain('t("federation.pendingBadge")');
    expect(src).toContain('t("federation.trustedBadge")');
    expect(src).toContain('t("federation.revokeTrust")');
    expect(src).not.toContain("This node");
    expect(src).not.toContain("Create invite");
    expect(src).not.toContain("Submit pairing request");
    expect(src).not.toContain("Incoming requests");
    expect(src).not.toContain("Trusted peers");
    expect(src).not.toContain("Invite another CCCC");
    expect(src).not.toContain("Join with a pairing code");
    expect(src).not.toContain("invite/request metadata, not direct registration");
    expect(src).toContain("<details");
  });

  it("trusted remote groups expose agent target ids without default peer or endpoint noise", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain('t("federation.remoteGroupId")');
    expect(src).toContain('t("federation.remoteGroupIdAgentHelp"');
    expect(src).toContain('t("federation.copyRecipientIdentifier"');
    expect(src).toContain("formatRecipientIdentifier");
    expect(src).toContain('t("federation.accessSummary"');
    expect(src).not.toContain('t("federation.remoteCccc"');
    expect(src).not.toContain('t("federation.unknownCccc"');
    expect(src).not.toContain('t("federation.remotePeerId"');
    expect(src).not.toContain('t("federation.remoteEndpoint"');
  });

  it("federation session pairing puts workbench actions before local diagnostics", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain('t("federation.localDiagnostics")');
    expect(src.indexOf('t("federation.connectRemoteCcccGroup")')).toBeLessThan(src.indexOf('t("federation.localDiagnostics")'));
    expect(src.indexOf('t("federation.createConnectionInfo")')).toBeLessThan(src.indexOf('t("federation.localDiagnostics")'));
    expect(src.indexOf('t("federation.pasteConnectionInfo")')).toBeLessThan(src.indexOf('t("federation.localDiagnostics")'));
    expect(src.indexOf('t("federation.incomingRequests")')).toBeLessThan(src.indexOf('t("federation.localDiagnostics")'));
    expect(src.indexOf('t("federation.trustedRemoteGroups")')).toBeLessThan(src.indexOf('t("federation.localDiagnostics")'));
  });

  it("federation session pairing uses local identity as request metadata instead of requester peer input", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    expect(src).toContain("requesterPeerId: localPeerId");
    expect(src).not.toContain("setRequestPeerId");
    expect(src).not.toContain('t("federation.yourPeerId")');
  });

  it("federation session diagnostics do not present invite metadata addresses as local addresses", () => {
    const src = readSource("./FederationSessionPairingSection.tsx");
    const diagnosticsStart = src.indexOf('t("federation.localDiagnostics")');
    expect(diagnosticsStart).toBeGreaterThan(0);
    const diagnosticsSrc = src.slice(diagnosticsStart);
    expect(diagnosticsSrc).toContain('t("federation.sessionTransport")');
    expect(diagnosticsSrc).toContain('t("federation.sessionTransportManaged")');
    expect(diagnosticsSrc).not.toContain("multiaddrs.join");
    expect(diagnosticsSrc).not.toContain("multiaddrsText");
  });

  it("Federation Settings user-facing copy lives in settings locale files", () => {
    const locales = [
      readJson("../../../i18n/locales/en/settings.json"),
      readJson("../../../i18n/locales/zh/settings.json"),
      readJson("../../../i18n/locales/ja/settings.json"),
    ] as Array<{ federation?: Record<string, unknown> }>;
    for (const locale of locales) {
      expect(locale.federation).toBeTruthy();
      expect(locale.federation?.modeHttp).toBeTruthy();
      expect(locale.federation?.modeSession).toBeTruthy();
      expect(locale.federation?.connectRemoteCcccGroup).toBeTruthy();
      expect(locale.federation?.createConnectionInfo).toBeTruthy();
      expect(locale.federation?.issuerEndpoint).toBeTruthy();
      expect(locale.federation?.issuerEndpointHelp).toBeTruthy();
      expect(locale.federation?.issuerEndpointLocalOnlyHelp).toBeTruthy();
      expect(locale.federation?.issuerEndpointInvalid).toBeTruthy();
      expect(locale.federation?.unsafeIssuerEndpointBlocked).toBeTruthy();
      expect(locale.federation?.sha256Unavailable).toBeTruthy();
      expect(locale.federation?.pasteConnectionInfo).toBeTruthy();
      expect(locale.federation?.remotePayloadPlaceholder).toBeTruthy();
      expect(locale.federation?.remotePayloadDetected).toBeTruthy();
      expect(locale.federation?.remotePayloadTarget).toBeTruthy();
      expect(locale.federation?.sameInstanceFallbackDetected).toBeTruthy();
      expect(locale.federation?.sameInstanceFallbackHelp).toBeTruthy();
      expect(locale.federation?.incomingRequests).toBeTruthy();
      expect(locale.federation?.trustedPeers).toBeTruthy();
      expect(locale.federation?.pendingBadge).toBeTruthy();
      expect(locale.federation?.trustedBadge).toBeTruthy();
      expect(locale.federation?.copyRecipientIdentifier).toBeTruthy();
      expect(locale.federation?.copyRecipientIdentifierDone).toBeTruthy();
      expect(locale.federation?.copyRecipientIdentifierManual).toBeTruthy();
      expect(locale.federation?.advancedInviteMetadata).toBeTruthy();
      expect(locale.federation?.localDiagnostics).toBeTruthy();
      expect(locale.federation?.localDiagnosticsHelp).toBeTruthy();
      expect(locale.federation?.sessionTransport).toBeTruthy();
      expect(locale.federation?.sessionTransportManaged).toBeTruthy();
      expect(locale.federation?.legacyHttpTitle).toBeUndefined();
      expect(locale.tabs?.connections).toBeTruthy();
      expect(locale.tabs?.federation).toBeUndefined();
    }
  });
});
