gates:
  irreversible_changes: { requires: ["peerA","peerB"] }   # 架构/数据迁移/公开API
  release_tag:          { requires: ["peerA","peerB"] }
rfd:
  trigger:
    both_confidence_below: 0.6
    max_dispute_rounds: 2
  default_option_required: true
patch_queue:
  max_diff_lines: 150
  allowed_paths: ["src/**","tests/**","docs/**","infra/**"]
  prechecks: ["git-apply-check","lint","quick-tests"]
autonomy_level: L1   # 初期谨慎；稳定后改为 L2/L3
