leader: peerA             # 初期由用户指定
specialties:
  peerA:
    - product-shaping
    - architecture
    - security-review
  peerB:
    - implementation
    - testing
    - performance
rotation:
  mode: manual            # 手动；仅阶段切换或僵局时更换
  allowed_at: [ "phase-change", "stalemate" ]
