name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install -U pip build twine

      - name: Sync scaffold
        run: |
          python scripts/sync_scaffold.py

      - name: Build
        run: |
          python -m build

      - name: Determine repository
        id: repo
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "${TAG}" == *"-rc"* || "${TAG}" == *"-alpha"* || "${TAG}" == *"-beta"* ]]; then
            echo "name=testpypi" >> $GITHUB_OUTPUT
            echo "url=https://test.pypi.org/legacy/" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.TEST_PYPI_API_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "name=pypi" >> $GITHUB_OUTPUT
            echo "url=https://upload.pypi.org/legacy/" >> $GITHUB_OUTPUT
            echo "token=${{ secrets.PYPI_API_TOKEN }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload to ${{ steps.repo.outputs.name }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ steps.repo.outputs.token }}
        run: |
          python -m twine upload --repository-url "${{ steps.repo.outputs.url }}" dist/*

